export enum AxonTestId {
  LanguageDetectorShortStringColdStart = "Identify language of a common, short phrase. Cold Start.",
  LanguageDetectorShortStringWarmStart = "Identify language of a common, short phrase. Warm Start.",
  TranslatorShortStringEnglishToFrenchColdStart = "Translate short phrase from english to french. Cold Start.",
  TranslatorShortStringEnglishToFrenchWarmStart = "Translate short phrase from english to french. Warm Start.",
  SummarizerLongNewsArticleColdStart = "Summarize a long news article. Cold Start.",
  SummarizerLongNewsArticleWarmStart = "Summarize a long news article. Warm Start.",
  PromptTextFactAnalysisColdStart = "Prompt (Text). Analyze the scenario and provide a response. Cold Start.",
  PromptTextEthicalAndCreativeColdStart = "Prompt (Text). Answer Ethical Dilemma, then creative task. Cold Start.",
  PromptTextTechnicalChallengeColdStart = "Prompt (Text). Technical challenge, write code. Cold Start.",
  PromptImageOcrHandwrittenColdStart = "Prompt Image OCR Handwritten (Cold)",
  PromptImageOcrComputerFontColdStart = "Prompt Image OCR Computer Font (Cold)",
  PromptImageDescribeColdStart = "Prompt Image Describe (Cold)",
  PromptImageExplainMemeColdStart = "Prompt Image Explain Meme (Cold)",
  PromptImageExplainEmotionColdStart = "Prompt Image Explain Emotion (Cold)",
}
