export enum AxonTestId {
  LanguageDetectorShortStringColdStart = "Identify language of a common, short phrase. Cold Start.",
  LanguageDetectorShortStringWarmStart = "Identify language of a common, short phrase. Warm Start.",
  TranslatorShortStringEnglishToFrenchColdStart = "Translate short phrase from english to french. Cold Start.",
  TranslatorShortStringEnglishToFrenchWarmStart = "Translate short phrase from english to french. Warm Start.",
  SummarizerLongNewsArticleColdStart = "Summarize a long news article. Cold Start.",
  SummarizerLongNewsArticleWarmStart = "Summarize a long news article. Warm Start.",
  PromptTextFactAnalysisColdStart = "Prompt (Text). Analyze the scenario and provide a response. Cold Start.",
  PromptTextEthicalAndCreativeColdStart = "Prompt (Text). Answer Ethical Dilemma, then creative task. Cold Start.",
  PromptTextTechnicalChallengeColdStart = "Prompt (Text). Technical challenge, write code. Cold Start.",
  PromptImageOcrHandwrittenLetter1ColdStart = "Prompt Image OCR Handwritten Letter 1 (Cold)",
  PromptImageOcrHandwrittenLetter2ColdStart = "Prompt Image OCR Handwritten Letter 2 (Cold)",
  PromptImageOcrHandwrittenLetter3ColdStart = "Prompt Image OCR Handwritten Letter 3 (Cold)",
  PromptImageOcrHandwrittenName1ColdStart = "Prompt Image OCR Handwritten Name 1 (Cold)",
  PromptImageOcrHandwrittenName2ColdStart = "Prompt Image OCR Handwritten Name 2 (Cold)",
  PromptImageOcrHandwrittenName3ColdStart = "Prompt Image OCR Handwritten Name 3 (Cold)",
  PromptImageOcrComputerFontColdStart = "Prompt Image OCR Computer Font (Cold)",
  PromptImageDescribeColdStart = "Prompt Image Describe (Cold)",
  PromptImageExplainMemeColdStart = "Prompt Image Explain Meme (Cold)",
  PromptImageExplainEmotionColdStart = "Prompt Image Explain Emotion (Cold)",
  PromptAudioTranscription119ColdStart = "Prompt Audio Transcription 119 (Cold)",
  PromptAudioTranscription4167ColdStart = "Prompt Audio Transcription 4167 (Cold)",
  PromptAudioTranscription46ColdStart = "Prompt Audio Transcription 46 (Cold)",
  PromptAudioTranscription5670ColdStart = "Prompt Audio Transcription 5670 (Cold)",
}
